name: Compile PDF Github action
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compiel Latex document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Dissertation.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Dissertation
          path: Dissertation.pdf
      - name: Create prerelease
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # GitHub secret token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # Git tag (for automatic releases)
          automatic_release_tag: "latest" # optional
          # Assets to upload to the release
          files: Dissertation.pdf
              
